ALTER TABLE Package
    ADD COLUMN nativeTargets TEXT NOT NULL DEFAULT '';
ALTER TABLE Package
    ADD COLUMN capabilities TEXT NOT NULL DEFAULT '';

ALTER TABLE DocGenJob
    ADD COLUMN useNative BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE DocGenJob
    ADD COLUMN capabilities TEXT NOT NULL DEFAULT '';
